"""Canonical event -> strict 4-field schema + detail-grounding check (PLAN.md S3/S4/S6).

`detail` is composed deterministically FROM the canonical event's own
structured fields (clinical_facts / status / attribution) rather than
freely generated by an LLM -- this is the grounding guarantee itself: a
templated sentence built only from fields that already traced back to
evidence during extraction cannot introduce a new fact the way a fresh
LLM-written sentence could. No LLM call in this stage.

Unresolved-conflict policy (PLAN.md S6, restated here where it's enforced):
a high-materiality event with needs_review=True never gets a confidently-
worded final value. If the unresolved field is `date`, the projection uses
`date: null` (the schema's "no date recoverable" case, used here as a
documented conservative fallback for "recoverable but genuinely disputed",
not a claim about the schema's literal wording). If it's a clinical_facts
field, the sentence states the disagreement in plain language instead of
picking a side. Low-materiality unresolved events are dropped rather than
building special-case machinery for routine content.
"""

from __future__ import annotations

import re
from typing import Any, Optional

from chronos import timeline as chronos_timeline
from evalkit.extraction.canonicalize import CanonicalEvent

_STOPWORDS = {
    "the", "a", "an", "of", "for", "and", "or", "with", "to", "on", "in",
    "at", "by", "was", "were", "is", "left", "right", "patient",
}


def _significant_words(text: str) -> set[str]:
    return {w for w in re.findall(r"[a-z0-9]+", (text or "").lower()) if w not in _STOPWORDS and len(w) > 2}


# A model's OWN self-disclosed hedge that it decoded a bare billing/procedure
# code using outside medical-coding knowledge, not the source text (the exact
# rule EXTRACTION_SYSTEM_PROMPT already forbids -- this is a deterministic
# backstop for when the model violates it anyway, found via real case-davis
# output: "Peripheral nerve (per CPT code convention, not clinically
# confirmed in text)", "Lower limb (per code convention, not narratively
# confirmed)", "postprocedural scoliosis, per code, but not clinically
# confirmed in this chunk" -- all three share this exact phrasing pattern,
# a much more precise and reliable signal than word-overlap grounding, which
# either missed these (the code fragment itself, e.g. "M96", trivially
# "grounds" the whole hedge-wrapped phrase it's attached to) or -- tried and
# reverted after real-data testing -- over-triggered on genuinely correct,
# just differently-worded body_site/laterality values elsewhere in the same
# corpus (FINDINGS.md/DECISIONS.md: e.g. "left arm" dropped from a follow-up
# note whose own evidence snippet just said "amputation", still true, just
# not restated word-for-word in that one snippet).
_SELF_HEDGED_DECODE_RE = re.compile(
    r"\bper (cpt |icd )?code(\s+convention)?\b|\bnot (clinically|narratively) confirmed\b",
    re.IGNORECASE,
)


def _is_self_hedged_decode(phrase: str) -> bool:
    return bool(_SELF_HEDGED_DECODE_RE.search(phrase or ""))


def _is_grounded(phrase: str, evidence_words: set[str]) -> bool:
    """Deterministic grounding check: does this interpreted clinical_facts
    value share any significant word with the actual cited evidence text?

    Catches the failure mode found in the real case-vance run: extraction
    populated clinical_facts.procedure with "open treatment of tibial
    plateau fracture" (real-world knowledge of what CPT 27535 means) for a
    billing line that only ever said "Operating Room Services, 27535" --
    correct in general, wrong for this patient (arm fractures, not a knee),
    and not actually stated anywhere in the source. A templated sentence
    built from clinical_facts is only as grounded as clinical_facts itself;
    this check is what actually enforces that, not the templating alone.

    Also rejects a phrase carrying its own self-hedged-decode disclaimer
    (see _SELF_HEDGED_DECODE_RE) outright, before the word-overlap check --
    found necessary because the hedge text itself, or the bare code it's
    attached to, can trivially share a word with the evidence (e.g. "M96"
    appearing in both), which would otherwise let the whole hedge-wrapped
    invented phrase through.
    """
    if _is_self_hedged_decode(phrase):
        return False
    phrase_words = _significant_words(phrase)
    if not phrase_words:
        return True  # nothing to check
    # A shared billing/CPT code alone doesn't ground an interpretation of what
    # that code means -- "27535" appearing in both the phrase and the source
    # is trivially true and exactly the case that slipped through un-checked
    # (the code was real, the "tibial plateau fracture" gloss on it wasn't).
    # Require overlap on a non-numeric word when the phrase has one to offer.
    non_numeric_phrase_words = {w for w in phrase_words if not w.isdigit()}
    if non_numeric_phrase_words:
        return bool(non_numeric_phrase_words & evidence_words)
    return bool(phrase_words & evidence_words)


STATUS_QUALIFIER = {
    "performed": None, "reported_history": None,
    "ordered": "ordered", "recommended": "recommended",
    "planned": "planned", "considered": "considered", "cancelled": "cancelled",
}


def _primary_clause(event: CanonicalEvent) -> Optional[str]:
    cf = event.clinical_facts or {}
    evidence_words = _significant_words(" ".join(str(e.get("snippet") or "") for e in event.evidence))

    main = None
    for candidate_field in ("procedure", "diagnosis_or_finding", "concept"):
        value = cf.get(candidate_field)
        if value and _is_grounded(value, evidence_words):
            main = value
            break
    if main is None:
        # Every interpreted value failed the grounding check (or none exist) --
        # fall back to the raw evidence snippet itself, which is grounded by
        # construction, rather than a specific interpretation that isn't.
        raw_snippet = event.evidence[0].get("snippet") if event.evidence else None
        return raw_snippet.strip().rstrip(".") if raw_snippet else None

    lat, site = cf.get("laterality"), cf.get("body_site")
    # Self-hedge check applies here too, not just to procedure/diagnosis_or_finding/concept
    # (FINDINGS.md: a real, confirmed gap -- body_site/laterality were appended completely
    # unchecked, which is exactly how a hedged-but-still-decoded value like body_site=
    # "peripheral nerve (per CPT code convention, not clinically confirmed in text)" reached
    # a committed final timeline for case-davis). Deliberately the NARROW hedge-phrase check
    # only, NOT the full word-overlap _is_grounded() check -- tried the full check first and
    # reverted after real-data testing found it stripped plenty of genuinely correct,
    # just-differently-worded body_site values (e.g. "left arm" from a follow-up note whose
    # own evidence snippet just said "amputation", still true, never restated verbatim in
    # every single snippet). A self-disclosed "I decoded this from a bare code" hedge is a
    # precise, reliable signal; requiring literal word-repetition in one specific evidence
    # snippet is not.
    if site and _is_self_hedged_decode(site):
        site = None
    if lat and _is_self_hedged_decode(lat):
        lat = None
    # site can already embed the laterality (e.g. body_site="left humerus/radius",
    # laterality="left") -- check lat against site too, not just against main,
    # or a redundant "left left humerus..." results.
    lat_redundant = lat and site and lat.lower() in site.lower()
    if lat and not lat_redundant and site and lat.lower() not in main.lower() and site.lower() not in main.lower():
        main = f"{lat} {site} {main}"
    elif site and site.lower() not in main.lower():
        main = f"{site} {main}"
    elif lat and not lat_redundant and lat.lower() not in main.lower():
        main = f"{lat} {main}"
    medication, dose = cf.get("medication"), cf.get("dose")
    if medication:
        main = f"{main}: {medication}" + (f" {dose}" if dose else "") if main != medication else main
    return main


def _compose_detail(event: CanonicalEvent) -> Optional[str]:
    """Assemble `detail` from structured fields only. Returns None if there's
    not enough grounded content to write an honest sentence."""
    date_conflict = "unresolved conflict on 'normalized_date'" in event.review_reasons

    main = _primary_clause(event)
    if main is None:
        if not event.clinical_facts.get("medication"):
            return None
        main = event.clinical_facts["medication"]

    sentence = main[0].upper() + main[1:] if main else main
    qualifier = STATUS_QUALIFIER.get(event.status)
    if qualifier:
        sentence += f" ({qualifier})"

    provider = (event.attribution or {}).get("provider")
    if provider:
        sentence += f", {provider}"
    elif "unresolved conflict on 'provider'" in event.review_reasons:
        sentence += " (provider disputed across sources -- see evidence)"

    if date_conflict:
        conflicting = sorted(
            {
                str(e.get("note", "")).split("=", 1)[-1].split(",", 1)[0]
                for e in event.evidence
                if e.get("note") and "normalized_date" in e.get("note", "")
            }
        )
        if conflicting:
            sentence += f"; sources disagree on the date ({', '.join(conflicting)})"

    sentence = sentence.strip()
    if not sentence.endswith("."):
        sentence += "."
    return sentence[:600]


def project_event(event: CanonicalEvent) -> Optional[dict[str, Any]]:
    """One canonical event -> one strict-schema timeline event, or None if
    it shouldn't be projected (no confident date+content and low materiality,
    or nothing grounded enough to write a detail sentence at all)."""
    date_conflict = "unresolved conflict on 'normalized_date'" in event.review_reasons
    date = None if date_conflict else event.date

    detail = _compose_detail(event)
    if detail is None:
        return None  # nothing grounded enough to state -- drop rather than fabricate

    if event.needs_review and event.materiality != "high":
        return None  # low-materiality unresolved conflict: simplest safe default is to omit it

    source = None
    if event.evidence:
        # Prefer an evidence entry that WON its conflicts (no "note" flagging it
        # as a losing value) -- citing the first entry regardless would risk
        # pointing a reviewer at, e.g., the billing form for a date/provider
        # that was actually resolved from the operative report instead.
        winning = [e for e in event.evidence if not e.get("note")]
        primary = winning[0] if winning else event.evidence[0]
        source = f"{primary.get('doc')} p{primary.get('page')}" if primary.get("page") else primary.get("doc")

    return {
        "date": date,
        "type": event.type,
        "detail": detail,
        "source": source or "",
    }


def project_events(events: list[CanonicalEvent]) -> tuple[list[dict], list[dict]]:
    """Returns (valid_timeline_events, validation_problems) -- the caller
    should not send anything to /v1/summarize until problems is empty."""
    projected = [p for p in (project_event(e) for e in events) if p is not None]
    try:
        chronos_timeline.parse({"events": projected})
        return projected, []
    except chronos_timeline.TimelineError as exc:
        return projected, [{"problem": p} for p in exc.problems]
